spring:
  application:
    name: java-spring-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java-spring-api?useTimezone=true&serverTimezone=UTC
    username: root
    password: toor
  jpa:
    open-in-view: false
    show_sql: false
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
logging:
  level:
    root: WARN
    # com.fhbhub.javaspringapi: WARN
