CREATE TABLE `books` (
  `id` INT(10) AUTO_INCREMENT PRIMARY KEY,
  `title` LONGTEXT NOT NULL,
  `author` LONGTEXT NOT NULL,
  `launch_date` DATE,
  `price` DECIMAL(6,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
